### PR TITLE
Added rubocop

### PR DESCRIPTION
**Pull request by paradime**
That was way easier than I thought

### CODE REVIEW

**Comment by nickserv** [comment]
Nice activity! It's cool to see more of a focus on code style.

**Comment by nickserv** [comment]
I already merged this, though I noticed that this is a little advanced for a beginner's activity in my opinion (especially since it involves specifics of Ruby syntax).

How would you feel about moving this to one of the following sections?
- Automated Testing
- Intermediate
- Extra Credit

**Comment by nickserv** [comment]
CC @jaybobo for my previous comment

**Comment by jaybobo** [comment]
Good points @nicolasmccurdy, let's move it to automated testing. Hope all is well dude, we should catch up soon. I'd love to know how things are going out in Boston!

**Pull request merged**
