### PR TITLE
moar images

### PR DESCRIPTION
**Pull request by jaybobo**
Addresses some of #13

### CODE REVIEW

**Comment by nickserv** [comment]
Awesome!

I would like to trim the extra space off of the logos and make a scaled copy of the navbar logo. I would also like to make the favicon retina ready (if it isn't already) and transparent. If that's OK with you, I can work on that on this branch.

By the way, is the non-transparent logo used anywhere?

**Comment by jaybobo** [comment]
The non-transparent logo isn't used but I figured we'll need it sooner or later.

The favicon isn't retina ready. I created it at 16x16 :(

**Comment by nickserv** [comment]
I'm not sure if we would need the non transparent logo, we could always set the transparent one on a white background. And if we do need that back we can revert it.

Ah I see, I figured the favicon was just one of the computers scaled down. Is it, or is it drawn differently?

**Comment by jaybobo** [comment]
Updated the favicon for retina and I've added an eps vector file as well. I'm going to use GH as file storage in those frequent cases when someone asks for a logo.

**Pull request merged**
