### PR TITLE
Challenges data file

### LINKED ISSUE #5: Consolidate information about challenges in a hosted JSON file
As far as I'm aware, there are currently two lists of challenges:
- [ChallengeGuide.md](https://github.com/paircolumbus/Welcome/blob/master/ChallengeGuide.md) for humans
- [challenges.json](https://github.com/paircolumbus/progress/blob/master/challenges.json) for computers (currently only used for [progress](https://github.com/paircolumbus/progress))

It would be awesome if we could move the JSON file to this repository, host it (with a proper `Content-Type` header, which GitHub Pages fortunately does for you), and generate the human readable version from the JSON file to prevent duplicate data and make it easier to add new challenges. This isn't currently possible in an easy way because [ChallengeGuide.md](https://github.com/paircolumbus/Welcome/blob/master/ChallengeGuide.md) is just a plain Markdown file, but if #4 is merged we can move the challenge guide to the Jekyll site and autogenerate parts of it from the JSON file.

### PR DESCRIPTION
**Pull request by nickserv**
Fixes #5.

### CODE REVIEW

**Comment by nickserv** [comment]
Note that this serves the minified JSON at `/api/challenges.json` on the site. I'm not sure if we want to support this when we could just let someone download the raw JSON file from GitHub, though it's useful that the site's version sets the right `Content-Type` header.

Additionally, the challenge names on the challenges page have been changed so they're all exactly the names of their repository. It's not as pretty, but it makes things simpler. I'm thinking about using Jekyll filters to at least add spaces where there are capital letters.

Any thoughts about these concerns?

**Comment by nickserv** [comment]
CC @jaybobo

**Comment by jaybobo** [comment]
nice :+1:  this changes a few things for contributors but i feel like its all positive.

**Comment by nickserv** [comment]
Cool. Should I keep the API endpoint? Also, should I merge?

**Comment by jaybobo** [comment]
I feel like we spoke about already but this is good to go :+1: 

Once this is merged in, I'll ping GDI & Dev::Launch and let them know they can use it as an endpoint for their curriculum.

**Pull request merged**
