### PR TITLE
New site

### LINKED ISSUE #1: Move Welcome documents into this repository as separate pages
See the markdown documents in https://github.com/paircolumbus/Welcome.

### PR DESCRIPTION
**Pull request by nickserv**
This isn't 100% ready yet, but I'll leave this here in case anyone wants to comment or contribute.
# Changes
- Fixes #1
- Switch from the automatic GitHub Pages generator (which unfortunately doesn't support sites with more than one page) to the default Jekyll site template
  - **Note:** The template adds blogging support, but I removed it. If you want it back, revert commit ac26e65.
- Add all documents from paircolumbus/Welcome (as of c3a9b57)
  - Welcome pages are (usually) represented one-to-one as pages on the new site, and are also accessible from the navbar
  - If this is merged, we can deprecate/remove the Welcome repository
- Add emoji support :smile: and GitHub mention support
- Add @variousweapon and @jaybobo to the special thanks section (for contributing to the Welcome repository)
- Use the README.md and CONTRIBUTING.md from the Welcome repository **(incomplete)**
- Rename and reorganize some of the welcome pages
- Merge Submitting Challenges into Challenges (the new version of Challenge Guide)

### CODE REVIEW

**Comment by nickserv** [comment]
CC @jaybobo

**Comment by degoeym** [comment]
Might not be a bad idea to also include a link to GitHub's Markdown guide. https://guides.github.com/features/mastering-markdown/

**Comment by nicolasmccurdy** [comment]
Yes, they send notifications to people that are being mentioned, and they work in all Markdown documents and text rendered on GitHub. I also added a Jekyll plugin that supports them (though it doesn't send notifications).

**Comment by nickserv** [comment]
Good idea, though I want to focus this pull request on moving all existing resources to one place and formatting changes. I can add that to master if you'd like.

**Pull request merged**
